language: python
python:
  - 3.6
before_install:
  - sudo apt-get install software-properties-common
install:
  - python setup.py install
  - pip install coverage
script: 
notifications:
  webhooks:
    - https://lamden-discord-travisci.herokuapp.com/webhook/
