language: python
python:
  - 3.6
before_install:
  - sudo apt-get install software-properties-common
install:
  - pip install -r requirements.txt
  - pip install coverage
notifications:
  webhooks:
    - https://lamden-discord-travisci.herokuapp.com/webhook/
