language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install software-properties-common
install: "python setup.py develop"
script: 
notifications:
  webhooks:
    - https://lamden-discord-travisci.herokuapp.com/webhook/
