version: 2
jobs:
  build:
    machine:
        image: circleci/classic:201808-01
    working_directory: ~/cilantro
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages
      # - restore_cache:
      #     key: cilantro-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: docker pull lamden/cilantro-db
      - run: pyenv local 3.6.5
      - run: export PYTHONPATH=~/cilantro
      - run:
          name: Install Cilantro Requirements
          command: |
             sudo apt-get install libmysqlclient-dev
             pip install -r requirements.txt --upgrade --no-cache-dir --exists-action w
             pip install -r dev-requirements.txt --upgrade --no-cache-dir --exists-action w
      - run:
          name: Install Mysql Client
          command: |
             sudo apt install -y mysql-client

      - run:
          name: set temp credentials file (aka db config stuff)
          command: |
             ./scripts/make_test_config.py --password buttcoins --username cilantro_user --database cilantro_dev --hostname 127.0.0.1

      - save_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages"

      - run:
          name: Check for Custom Seneca Branch Injected by REST API
          command: |
            if [ -z "$SENECA_BRANCH" ]; then
              echo "SENECA_BRANCH env variable is not set"
            else
              echo "SENECA_BRANCH is set to $SENECA_BRANCH"
              pip3 install git+https://github.com/Lamden/seneca.git@$SENECA_BRANCH#egg=seneca --no-cache-dir --upgrade
            fi

      - run:
          name: Wait For mysqld
          command: |
            make start-db

      - run:
          name: Run Tests
          command: |
            export PYTHONPATH=$PYTHONPATH:~/cilantro
            export LOCAL_PATH=~
            python3.6 ~/cilantro/tests/run_tests.py --integration 1 --unit 0

      - store_artifacts:
          path: test-results
          destination: tr1
