version: 2
jobs:
  build:
    working_directory: ~/cilantro
    docker:
      - image: circleci/python:3.6.5
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: lamden/cilantro:firsttry
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install -r requirements.txt
            pipenv install -r dev-requirements.txt
      - save_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
      - run:
          command: |
            export PYTHONPATH=$PYTHONPATH:~/cilantro
            export LOCAL_PATH=~
            pipenv run python ~/cilantro/tests/test_runner.py
      - store_artifacts:
          path: test-results
          destination: tr1