version: 2
jobs:
  build:
    working_directory: ~/cilantro
    machine:
      - image: circleci/python:3.6.5
        environment:
          PIPENV_VENV_IN_PROJECT: true
#      - run:
#          command: |
#            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#            chmod +x ~/docker-compose
#            sudo mv ~/docker-compose /usr/local/bin/docker-compose
#      - image: lamden/cilantro:firsttry
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Cilantro Requirements
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Run Docker Daemon
          command: |
            dockerd &
      - save_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"

      - run:
          command: |
            export PYTHONPATH=$PYTHONPATH:~/cilantro
            export LOCAL_PATH=~
            pipenv run python ~/cilantro/tests/test_runner.py
      - store_artifacts:
          path: test-results
          destination: tr1
